import 'package:shop_app/src/objects/food_class.dart';

List<Food> vegetablesList = <Food>[
  Food(
      title: 'Лук репчатый, кг',
      desc: 'Состав: Лук.',
      weight: 1000,
      expDate: '9 дней, 0 ℃',
      price: 59.99,
      salePrice: 49.99,
      count: 54,
      brand: 'Овощная База',
      calories: 40,
      fat: 0.1,
      protein: 1.1,
      carbohydrate: 9,
      img: 'assets/images/onion.webp'
  ),
  Food(
      title: 'Салат Мини Шпинат, 65г',
      desc: 'Состав: Салат Мини Шпинат.',
      weight: 65,
      expDate: '9 дней, 2-4 ℃',
      price: 119.99,
      salePrice: 119.99,
      count: 64,
      brand: 'Овощная База',
      calories: 23,
      fat: 0.3,
      protein: 2.9,
      carbohydrate: 2,
      img: 'assets/images/salat.webp'
  ),
  Food(
      title: 'Томаты черри на ветке, 250г',
      desc: 'Состав: Томаты.',
      weight: 250,
      expDate: '30 дней, 5 ℃',
      price: 209.99,
      salePrice: 189.99,
      count: 25,
      brand: 'Овощная База',
      calories: 15,
      fat: 0.1,
      protein: 1.8,
      carbohydrate: 2.8,
      img: 'assets/images/cherry_tomatoes.webp'
  ),
  Food(
      title: 'Огурцы Фасованные, 450г',
      desc: 'Состав: Огурцы.',
      weight: 450,
      expDate: '9 дней, 2 ℃',
      price: 119.99,
      salePrice: 119.99,
      count: 3,
      brand: 'Овощная База',
      calories: 14,
      fat: 0.1,
      protein: 0.8,
      carbohydrate: 2.5,
      img: 'assets/images/cucumber.webp'
  ),
  Food(
      title: 'Перец красный сладкий, кг',
      desc: 'Состав: Перец.',
      weight: 1000,
      expDate: '9 дней, 0 ℃',
      price: 239.99,
      salePrice: 239.99,
      count: 200,
      brand: 'Овощная База',
      calories: 27,
      fat: 0.1,
      protein: 1.3,
      carbohydrate: 5.3,
      img: 'assets/images/sweet_pepper.webp'
  ),
  Food(
      title: 'Картофель в сетке, кг',
      desc: 'Состав: Картофель.',
      weight: 1000,
      expDate: '9 дней, 0 ℃',
      price: 32.99,
      salePrice: 29.99,
      count: 2000,
      brand: 'Овощная База',
      calories: 80,
      fat: 0.4,
      protein: 2.0,
      carbohydrate: 18.1,
      img: 'assets/images/potato.webp'
  ),
];

List<Food> bakeryList = <Food>[
  Food(
      title: 'Плетёнка с кунжутом, 290г',
      desc: 'Состав: Мука пшеничная в/с, вода питьевая, опара (мука пшеничная в/с, вода питьевая, дрожжи прессованные хлебопекарные, сахар), молоко питьевое м. д. ж. 3,2%, желток пастеризованный, сахар, сливочное масло (сливки пастеризованные) «Крестьянское» м. д. ж. 72,5%, дрожжи прессованные хлебопекарные, соль пищевая, кунжут. Продукция изготавливается на предприятии, где используются аллергены: орехи и арахис.',
      weight: 290,
      expDate: '3 дня, 6-25 ℃',
      price: 79.99,
      salePrice: 65.99,
      count: 18,
      brand: 'Наша пекарня',
      calories: 292,
      fat: 9,
      protein: 3.5,
      carbohydrate: 56,
      img: 'assets/images/bread_sesame.webp'
  ),
  Food(
      title: 'Хлеб Кукурузный с сыром, 200г',
      desc: 'Состав: Мука пшеничная высшего сорта, вода питьевая, смесь хлебопекарная (семена подсолнечника, мука пшеничная, кукуруза воздушная(крупка), продукт экструзионной технологии (крупка кукурузная, краситель пищевой бета-каротин, глютен пшеничный, сыворотка молочная подсырная сухая, продукт экструдированных круп и зернового сырья кукурузный, мука кукурузная крупного помола, ароматизатор пищевой, пряности, технологические вспомогательные средства: ферментные препараты микробного происхождения), сыр гауда (молоко нормализованное коровье, соль, закваска мезофильных и мезофильно-термофильных молочнокислых бактерий, препарат ферментный молокосвертывающий животного происхождения, уплотнитель хлорид кальция, краситель натуральный Аннато WS), сахар, масло подсолнечное рафинированное, соль, дрожжи прессованные. Может содержать яйцо, молоко, кунжут, орехи.',
      weight: 200,
      expDate: '2 дня, 6-25 ℃',
      price: 99.99,
      salePrice: 79.99,
      count: 8,
      brand: 'Наша пекарня',
      calories: 333,
      fat: 7,
      protein: 12,
      carbohydrate: 55,
      img: 'assets/images/bread_corn_cheese.webp'
  ),
  Food(
      title: 'Хлеб Щедрый Дар, 285г',
      desc: 'Состав: Мука ржаная хлебопекарная сеяная, ядро семян подсолнечника, мука пшеничная второго сорта, солод ржаной сухой, сахар, концентрат квасного сусла, смесь сухая хлебопекарная «Солодовая -5» (мука ячменная, солод ржаной ферментированный, краситель сахарный колер), соль йодированная, дрожжи, сухая клейковина, вода. Возможны следы кунжута, орехов.',
      weight: 285,
      expDate: '3 дня, 6-25 ℃',
      price: 69.00,
      salePrice: 69.00,
      count: 12,
      brand: 'Наша пекарня',
      calories: 280,
      fat: 10,
      protein: 11,
      carbohydrate: 34,
      img: 'assets/images/bread_cereal.webp'
  ),
  Food(
      title: 'Фламиш с ветчиной и сыром, 90г',
      desc: 'Состав: Мука пшеничная хлебопекарная в. с. , ветчина говяжья ( говядина, соль, животный белок, экстрат натурального белого перца), сыр «Российский» м. д. ж 50% (пастеризованное молоко с использованием мезофильных микроорганизмов, сычужно-говяжьего молокосвертывающего ферментного препарата животного происхождения, поваренной пищевой соли, уплотнителя хлорида кальция, консерванта нитрат калия ), яйцо куриное пищевое, вода питьевая, молоко питьевое 3,2%, маргарин 82% жирности (рафинированные дезодорированные растительные масла в натуральном и отвержденном виде, вода, соль поваренная пищевая, эмульгаторы (Е322, Е471), ароматизатор идентичный натуральному «Сливки» , регулятор кислотности: лимонная кислота, краситель пищевой: аннато (Е160b), куркумин (Е100)), сахар белый, дрожжи прессованные хлебопекарные, соль поваренная пищевая.',
      weight: 90,
      expDate: '1 день, 6-25 ℃',
      price: 59.99,
      salePrice: 59.99,
      count: 31,
      brand: 'Наша пекарня',
      calories: 321,
      fat: 11.6,
      protein: 11.4,
      carbohydrate: 20.3,
      img: 'assets/images/flumish.webp'
  ),
  Food(
      title: 'Кекс Шеф с изюмом, 250г',
      desc: 'Состав: Мука пшеничная, сахар, маргарин (содержит ароматизатор), изюм, меланж яичный, пудра сахарная, пекарский порошок (содержит муку пшеничную), соль, ароматизатор.',
      weight: 250,
      expDate: '5 дней, 15-21 ℃',
      price: 139.99,
      salePrice: 139.99,
      count: 1,
      brand: 'Наша пекарня',
      calories: 434,
      fat: 20.5,
      protein: 5.6,
      carbohydrate: 56.8,
      img: 'assets/images/cupcake_chef.webp'
  ),
];


List<Food> meatList = <Food>[
  Food(
      title: 'Мясо говяжье для бульона без кости',
      desc: 'Состав: Говядина.',
      weight: 1000,
      expDate: '2 дня, 2-6 ℃',
      price: 749.99,
      salePrice: 649.99,
      count: 232,
      brand: 'Фуд-Маркет',
      calories: 105,
      fat: 7,
      protein: 22,
      carbohydrate: 0,
      img: 'assets/images/beef_without_bone.webp'
  ),
  Food(
      title: 'Шейная часть говяжья без кости',
      desc: 'Состав: Говядина.',
      weight: 1000,
      expDate: '2 дня, 2-6 ℃',
      price: 809.99,
      salePrice: 669.99,
      count: 222,
      brand: 'Фуд-Маркет',
      calories: 179,
      fat: 13,
      protein: 16,
      carbohydrate: 0,
      img: 'assets/images/neck_beef.webp'
  ),
  Food(
      title: 'Тушка цыплёнка 1 сорт охлаждённая',
      desc: 'Состав: Тушка цыплят-бройлеров 1-го сорта.',
      weight: 1000,
      expDate: '8 дней, 2-6 ℃',
      price: 169.00,
      salePrice: 169.00,
      count: 134,
      brand: 'Фуд-Маркет',
      calories: 190,
      fat: 14,
      protein: 16,
      carbohydrate: 34,
      img: 'assets/images/chicken.webp'
  ),
];


List<Food> fishList = <Food>[
  Food(
      title: 'Форель 1.5-2 кг потрошеная Карелия',
      desc: 'Состав: Форель охлажденная потрошеная.',
      weight: 1000,
      expDate: '12 дней, -2-0 ℃',
      price: 999.00,
      salePrice: 999.00,
      count: 23,
      brand: 'Фуд-Маркет',
      calories: 103,
      fat: 3,
      protein: 19,
      carbohydrate: 0,
      img: 'assets/images/trout.webp'
  ),
  Food(
      title: 'Дорадо Турция',
      desc: 'Состав: Дорадо.',
      weight: 1000,
      expDate: '15 дней, -2-0 ℃',
      price: 999.00,
      salePrice: 999.00,
      count: 333,
      brand: 'Фуд-Маркет',
      calories: 96,
      fat: 1,
      protein: 19,
      carbohydrate: 0,
      img: 'assets/images/dorado_turkey.webp'
  ),
  Food(
      title: 'Форель филе',
      desc: 'Состав: Форель.',
      weight: 1000,
      expDate: '9 дней, -2-0 ℃',
      price: 1749.00,
      salePrice: 1449.00,
      count: 5,
      brand: 'Фуд-Маркет',
      calories: 148,
      fat: 6,
      protein: 22,
      carbohydrate: 0,
      img: 'assets/images/trout_fillet.webp'
  ),
];


List<Food> favoriteList = <Food>[];

List<Food> shoppingCartList = <Food>[];